name: greet-email

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
      mail_to:
        description: "Recipient email address"
        required: true
jobs:
  greet:
    runs-on: ubuntu-latest
    environment: work-flow-env
    steps:
      - name: Send greeting mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ env.GMAIL_USER }}
          password: ${{secrets.GMAIL }}
          subject: "Greeting for visit"
          to: ${{env.MAIL_TO}}
          from: ${{ env.GMAIL_USER }}
          body: |
            Hello ${{env.name}}

            This is greeting from my github
